import pygame
from enum import auto

HMI_CONNECTION_ESTABLISHED = (auto(), "HMI_CONNECTION_ESTABLISHED")
HMI_CAR_CHANGED = (auto(), "HMI_CAR_CHANGED")
HMI_RPM_LEVEL_CHANGED = (auto(), "HMI_RPM_LEVEL_CHANGED")
RACE_NEW_LAP_STARTED = (auto(), "RACE_NEW_LAP_STARTED")
RACE_NEW_TRY_STARTED = (auto(), "RACE_NEW_TRY_STARTED")


HMI_VIEW_BUTTON_PRESSED = pygame.USEREVENT + 1
