import pygame

MAINMENU_START_PRESSED: int = pygame.USEREVENT + 1
MAINMENU_START_RELEASED: int = pygame.USEREVENT + 2
MAINMENU_SETTINGS: int = pygame.USEREVENT + 3
MAINMENU_SETTINGS_PRESSED: int = pygame.USEREVENT + 4
MAINMENU_SETTINGS_RELEASED: int = pygame.USEREVENT + 5

BACK_TO_MENU_PRESSED: int = pygame.USEREVENT + 6
BACK_TO_MENU_RELEASED: int = pygame.USEREVENT + 7

DROP_DOWN_PRESSED = pygame.USEREVENT + 8
DROP_DOWN_RELEASED = pygame.USEREVENT + 9
DROP_DOWN_SELECTED = pygame.USEREVENT + 10

ENTER_IP_OK_BUTTON_PRESSED = pygame.USEREVENT + 11
ENTER_IP_OK_BUTTON_RELEASED = pygame.USEREVENT + 12
ENTER_IP_KEYPAD_BUTTON_PRESSED = pygame.USEREVENT + 13
ENTER_IP_KEYPAD_BUTTON_RELEASED = pygame.USEREVENT + 14
ENTER_IP_DEL_BUTTON_PRESSED = pygame.USEREVENT + 15
ENTER_IP_DEL_BUTTON_RELEASED = pygame.USEREVENT + 16


CONNECTION_SUCCESS = pygame.USEREVENT + 17
CONNECTION_FAILED = pygame.USEREVENT + 18
